static_sites:
  - name: my-react-app
    build_command: npm install && npm run build
    publish: build/
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"